# Generated by Django 4.2 on 2026-03-22 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_completedorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeorders",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
