# Generated by Django 4.2 on 2026-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_activeorders_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedorder",
            name="status",
            field=models.CharField(
                choices=[("ready", "Ready to Collect"), ("collected", "Collected")],
                default="ready",
                max_length=20,
            ),
        ),
    ]
