# Generated by Django 4.2 on 2026-03-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_menu_price"),
        ("staff", "0004_completedorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedorder",
            name="item_name",
            field=models.CharField(default="Item (Deleted)", max_length=255),
        ),
        migrations.AlterField(
            model_name="completedorder",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.menu",
            ),
        ),
    ]
